
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RESTO = 16;
  public static final int CARACTER_RESERVADO = 25;
  public static final int FECHA_COMANDO = 3;
  public static final int BOOLEANO_RESERVADO = 24;
  public static final int MULTIPLICACAO = 12;
  public static final int SE = 27;
  public static final int PARAR = 40;
  public static final int INTEIRO_RESERVADO = 23;
  public static final int VIRGULA = 2;
  public static final int NEGACAO = 22;
  public static final int E = 19;
  public static final int EQUIVALENCIA = 18;
  public static final int IDENTIFICADOR = 38;
  public static final int OU = 20;
  public static final int CARACTER = 36;
  public static final int MAIS = 10;
  public static final int CONTINUAR = 39;
  public static final int ABRE_COLCHETE = 4;
  public static final int EOF = 0;
  public static final int DECIMAL = 33;
  public static final int DECIMAL_RESERVADO = 26;
  public static final int ABRE_BLOCO = 8;
  public static final int ABRE_PARENTESES = 6;
  public static final int error = 1;
  public static final int ENQUANTO = 29;
  public static final int OU_EXCLUSIVO = 21;
  public static final int FECHA_BLOCO = 9;
  public static final int MAIOR_QUE = 14;
  public static final int MENOS = 11;
  public static final int ESCREVA = 31;
  public static final int DIVISAO = 13;
  public static final int GUARDA = 32;
  public static final int FECHA_COLCHETE = 5;
  public static final int INTEIRO = 35;
  public static final int FECHA_PARENTESES = 7;
  public static final int ATRIBUICAO = 17;
  public static final int BOOLEANO = 34;
  public static final int STRING = 37;
  public static final int PARA = 30;
  public static final int RETORNAR = 41;
  public static final int MENOR_QUE = 15;
  public static final int SE_NAO = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VIRGULA",
  "FECHA_COMANDO",
  "ABRE_COLCHETE",
  "FECHA_COLCHETE",
  "ABRE_PARENTESES",
  "FECHA_PARENTESES",
  "ABRE_BLOCO",
  "FECHA_BLOCO",
  "MAIS",
  "MENOS",
  "MULTIPLICACAO",
  "DIVISAO",
  "MAIOR_QUE",
  "MENOR_QUE",
  "RESTO",
  "ATRIBUICAO",
  "EQUIVALENCIA",
  "E",
  "OU",
  "OU_EXCLUSIVO",
  "NEGACAO",
  "INTEIRO_RESERVADO",
  "BOOLEANO_RESERVADO",
  "CARACTER_RESERVADO",
  "DECIMAL_RESERVADO",
  "SE",
  "SE_NAO",
  "ENQUANTO",
  "PARA",
  "ESCREVA",
  "GUARDA",
  "DECIMAL",
  "BOOLEANO",
  "INTEIRO",
  "CARACTER",
  "STRING",
  "IDENTIFICADOR",
  "CONTINUAR",
  "PARAR",
  "RETORNAR"
  };
}

